apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-ecom-webapp
spec:
    defaultBackend:
        service:
            name: users-webapp-service
            port:
                number: 9090