apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-set
spec:
    serviceName: "mysql-0"
    selector:
        matchLabels:
            app: mysql
    updateStrategy:
        type: RollingUpdate
    replicas: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
            - name: mysql
              image: mysql/mysql-server:latest
              resources:
                limits:
                  memory: 2Gi
              ports:
              - containerPort: 3306
              volumeMounts:
                - name: mysql-data
                  mountPath: /usr/share/data
    volumeClaimTemplates:   # to create PVC
    - metadata:
        name: mysql-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi