apiVersion: v1
kind: Service
metadata:
  name: users-webapp-service
  labels:
    app: users-webapp
spec:
  type: {{ .Values.usersWebapp.service.type }}
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: users-webapp
  